


<script>

    setTimeout(() =>{
        console.log("Error Handling: try and catch 1");
    }, 1000);

    try{
        console.log(rahul);
    } catch(error){
        console.log('dsfsdf dsfdsfsdf');
    }

    setTimeout(() =>{
        console.log("Error Handling: try and catch 2");
    }, 2000);

    setTimeout(() =>{
        console.log("Error Handling: try and catch 3");
    }, 3000);

    setTimeout(() =>{
        console.log("Error Handling: try and catch 4");
    }, 5000);

</script>